### PR TITLE
Added rehydrate option to stop propagation listener

### PR DESCRIPTION
**Pull request by wachterjohannes**
**tasks:**
- [x] test coverage
- [ ] gather feedback for my changes

**informations:**

| q | a |
| --- | --- |
| Fixed tickets | none |
| BC breaks | none |
| Documentation PR | none |

### CODE REVIEW

**Comment by danrot** [comment]
Shouldn't that be targeted at develop?

**Comment by wachterjohannes** [comment]
you are totally right (:

**Comment by dantleech** [comment]
Didn't I make a PR like this?

**Comment by danrot** [comment]
At least I can't remember that.

**Pull request closed without merging**
