### PR TITLE
Fixed document-registry to handle locale

### PR DESCRIPTION
**Pull request by wachterjohannes**
fixes https://github.com/sulu-io/sulu-document-manager/issues/41, fixes https://github.com/sulu-io/sulu/issues/1647

this PR should also fix https://github.com/sulu-io/sulu/issues/1647

Additionally fixes "undefined" title for ghost pages!

### CODE REVIEW

**Comment by wachterjohannes** [comment]
if this changes are ok i will make this nice (: /cc @dantleech @danrot

**Comment by dantleech** [comment]
See comment in linked issue.

**Comment by wachterjohannes** [comment]
this is a simple test of the addition of locale to document registry. additional the content of this PR fixes a problem with sulu (undefined as title for ghost pages). i have splittet this into smaller PRs #43 and #44. if they are merged this can be closed.

**Comment by wachterjohannes** [comment]
this was fixed on another way ... i will close this

**Pull request closed without merging**
